# PARAMETRES CONNEXION BASE DE DONNEES
jdbc.driverClassName=com.mysql.jdbc.Driver

jdbc.url=jdbc\:mysql\:///?autoReconnect\=true

# Identifiants base de donnee
jdbc.username=
jdbc.password=

hibernate.show_sql=false
hibernate.dialect=org.hibernate.dialect.MySQLDialect

urlExt=https://localhost:8444
urlWSock=wss://localhost:8444
webapps=ged
smtp=postfix.leaderinfo.com
dossierRoot=C:/tools/applications/ged/data/

# Temps des sessions REST (exprime en milliseconde, 0=infini)
rest.sessionTime=600000

# Sert a annoter des PDF directement depuis la GED.
pspdfkitKey=
