#PARAMETRES CONNEXION BASE DE DONNEES
url=jdbc\:mysql\:///?autoReconnect\=true
database=
databaseEdi=

usernameNovanet=
passwordNovanet=
usernameSpring=
passwordSpring=
driver=com.mysql.jdbc.Driver

# PARAMETRES SPECIFIQUE A HIBERNATE
hibernate.show_sql=false
hibernate.dialect=org.hibernate.dialect.MySQLDialect

# PARAMETRES DU POOL DE CONNEXIONS
checkoutTimeout=10000
maxIdleTime=1800
maxConnectionAge=25200
acquireIncrement=5
maxStatements=180
propertyCycle=3
unreturnedConnectionTimeout=240
autoCommitOnClose=true
preferredTestQuery=SELECT nomSociete FROM societe WHERE 1=2
switchToManual=false

# VALEURS SPECIFQUES POUR CONNEXIONS JDBC ET HIBERNATE NOVANET (ANCIEN OBJETS)
minPoolSizeNormal=10
maxPoolSizeNormal=30

# VALEURS SPECIFIQUES POUR CONNEXIONS HIBERNATE SPRING (NOUVEAUX SERVICES)
minPoolSizeSpring=2
maxPoolSizeSpring=5

# AUTRES PARAMETRES BASE DE DONNEES
SGBD=MySQL
liquibaseEnabled=non

# PARAMETRES APPLICATION
environnement=DEV
webapps=novanet

# AUTRES PARAMETRES
boiteEnvoiBRB=E_MAIL
CouperRequetes=oui
connexionCourrier=
destanows=E_MAIL
Encoding=ISO-8859-1
Thawte=non
ipLocalGED=localhost:8444
from=novanet@leaderinfo.com
ipRemoteOOo=localhost:8443
ipLocalServeur=localhost:8443
ipLocalRequete=localhost:8443
ipRemoteServeur=localhost:8443
ipRemoteRequete=localhost:8443
LDAP=non
logsNovanet=non
MessageRefuDroit="Vous n'avez pas les droits !"
PropertyCycle=3
smtp=postfix.leaderinfo.com
serveurws=localhost:8443
SiteRetour=http\://www.leaderinfo.com
urlext=https\://localhost:8443/novanet/

saltValue=KuRJtEPlba

GlobalSSOLoginRedirectAuto=non
GlobalSSOLoginCreateAuto=oui
GlobalSSOLoginCredentialsForce=non

# PARAMETRES LIAISON NOVANET-WEBACTION
WebActionUrlDataBase=
WebActionDriverDataBase=com.mysql.jdbc.Driver
WebActionLoginDataBase=LOGIN_BDD
WebActionPasswordDataBase=PASSWORD_BDD
WebActionUrlServerApplication=https://localhost:8443
WebActionUrlServerApplicationTest=https://localhost:8443
WebActionUrlServerApplicationInterne=https://localhost:8443

#LOG
timeOutLogger=30000

#NovaNetCourrier
mailmerge=

# CFT
ipServerCFT=

# NEOHUB (en Mo)
neohub.upload.maxfilesize=1000
neohub.upload.maxgroupedfilesize=1000
