#PARAMETRES AUTHENTIFICATION WEBSERVICES
urlWebService=https://localhost:8443/novanet/

# Identifiants webservice Neo Core
login=
password=

# Style specifique
cssSocieteUser=

# Identifiants captcha google
keyPrivateCaptcha=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
keyPublicCaptcha=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
